# Generated by Django 4.0.5 on 2022-06-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.IntegerField()),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
            ],
        ),
    ]
